#!/bin/bash

# Run case
./Allclean > log.lbm
./Allpre > log.lbm
multiPhasePP --nht >  log.lbm
  
# Replace entries
sed -i 's/sigma 1.25/sigma 0.125/g' properties/macroProperties
sed -i 's/startTime 0;/startTime 600000;/g' properties/simulation
sed -i 's/endTime 600000;/endTime 2000000;/g' properties/simulation

# Run case
multiPhasePP --nht > log.lbm

sed -i 's/startTime 600000;/startTime 0;/g' properties/simulation
sed -i 's/endTime 2000000;/endTime 600000;/g' properties/simulation
